apiVersion: v1
kind: Service
metadata:
  name: caldera
  labels:
    app: caldera
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 32700
  selector:
    app: caldera
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caldera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caldera
  template:
    metadata:
      labels:
        app: caldera
    spec:
      containers:
      - name: caldera
        image: mitre/caldera:latest
        ports:
        - containerPort: 80
