apiVersion: v1
kind: ServiceAccount
metadata:
  name: battle-caldera-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caldera-v2
  namespace: battlefield
  labels: 
    app: caldera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caldera
  template:
    metadata:
      labels:
        app: caldera
    spec:
      serviceAccountName: battle-caldera-v2 
      containers:
      - name: caldera
        image: sleshme/cs9k-caldera:latest
        ports:
        - containerPort: 80
