apiVersion: v1
kind: Service
metadata:
  name: caldera
  labels:
    app: caldera
    
spec:
  type: NodePort
  ports:
    - name: webui 
      port: 8888
      nodePort: 32700
    - name: terminal
      targetPort: 5678
      port: 5678
  selector:
    app: caldera
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caldera
  namespace: battlefield
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caldera
  template:
    metadata:
      labels:
        app: caldera
    spec:
      containers:
      - name: caldera
        image: sleshme/cs9k-caldera:xssv2
        ports:
        - containerPort: 80
