apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  labels:
    app: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
    # namespace: battlefield
      labels:
        app: frigate
    spec:
      containers:
      - name: frigate
        image: alpine:latest
        command: ['tail']
        args: ['-f', '/dev/null']
        #ports:
        #- containerPort: 80




