apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: battlefield
  labels:
    app: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
      - name: frigate
        image: sleshme/cs9k-frigate:latest
        command: ["/bin/bash", "-c"]
        args: ["/tmp/callhome.sh"]
        ports:
        - containerPort: 6000




