apiVersion: v1
kind: Service
metadata:
  name: victim 
  labels:
    app: victim
spec:
  type: NodePort
  ports:
    - name: webui
      port: 8080
      nodePort: 32701
      targetPort: 3000
  selector:
    app: victim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victim
  namespace: battlefield
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victim
  template:
    metadata:
      labels:
        app: victim
    spec:
      containers:
      - name: victim 
        image: bkimminich/juice-shop 
        ports:
        - containerPort: 80




