apiVersion: v1
kind: Service
metadata:
  name: juice-shop 
spec:
  selector:
    app: victim
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  clusterIP: 10.96.0.42
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victim
  namespace: battlefield
  labels:
    app: victim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victim
  template:
    metadata:
      labels:
        app: victim
    spec:
      containers:
      - name: victim 
        image: bkimminich/juice-shop 




