apiVersion: apps/v1
kind: Deployment
metadata:
  name: caldera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caldera
  template:
    metadata:
      labels:
        app: caldera
    spec:
      containers:
      - name: caldera
        image: mitre/caldera:latest
        ports:
        - containerPort: 80