apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: caldera
  namespace: battlefield
spec:
  host: caldera
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: victim
  namespace: battlefield
spec:
  host: victim
